/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCommandRouteImport } from './routes/_authenticated/command'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedLabRouteImport } from './routes/_authenticated/lab'
import { Route as AuthenticatedOfficersRouteImport } from './routes/_authenticated/officers'
import { Route as AuthenticatedRegisterRouteImport } from './routes/_authenticated/register'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiPublicGatewayHeartbeatRouteImport } from './routes/api/public/gateway-heartbeat'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiStreamTelemetryRouteImport } from './routes/api/stream/telemetry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommandRoute = AuthenticatedCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabRoute = AuthenticatedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfficersRoute = AuthenticatedOfficersRouteImport.update({
  id: '/officers',
  path: '/officers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegisterRoute = AuthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGatewayHeartbeatRoute =
  ApiPublicGatewayHeartbeatRouteImport.update({
    id: '/api/public/gateway-heartbeat',
    path: '/api/public/gateway-heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamTelemetryRoute = ApiStreamTelemetryRouteImport.update({
  id: '/api/stream/telemetry',
  path: '/api/stream/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/command': typeof AuthenticatedCommandRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/lab': typeof AuthenticatedLabRoute
  '/officers': typeof AuthenticatedOfficersRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/report': typeof AuthenticatedReportRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/gateway-heartbeat': typeof ApiPublicGatewayHeartbeatRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/stream/telemetry': typeof ApiStreamTelemetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/command': typeof AuthenticatedCommandRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/lab': typeof AuthenticatedLabRoute
  '/officers': typeof AuthenticatedOfficersRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/report': typeof AuthenticatedReportRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/gateway-heartbeat': typeof ApiPublicGatewayHeartbeatRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/stream/telemetry': typeof ApiStreamTelemetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/command': typeof AuthenticatedCommandRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/lab': typeof AuthenticatedLabRoute
  '/_authenticated/officers': typeof AuthenticatedOfficersRoute
  '/_authenticated/register': typeof AuthenticatedRegisterRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/gateway-heartbeat': typeof ApiPublicGatewayHeartbeatRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/stream/telemetry': typeof ApiStreamTelemetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/command'
    | '/devices'
    | '/lab'
    | '/officers'
    | '/register'
    | '/report'
    | '/api/tts'
    | '/api/public/gateway-heartbeat'
    | '/api/public/ingest'
    | '/api/stream/telemetry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/command'
    | '/devices'
    | '/lab'
    | '/officers'
    | '/register'
    | '/report'
    | '/api/tts'
    | '/api/public/gateway-heartbeat'
    | '/api/public/ingest'
    | '/api/stream/telemetry'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/command'
    | '/_authenticated/devices'
    | '/_authenticated/lab'
    | '/_authenticated/officers'
    | '/_authenticated/register'
    | '/_authenticated/report'
    | '/api/tts'
    | '/api/public/gateway-heartbeat'
    | '/api/public/ingest'
    | '/api/stream/telemetry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiPublicGatewayHeartbeatRoute: typeof ApiPublicGatewayHeartbeatRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiStreamTelemetryRoute: typeof ApiStreamTelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/command': {
      id: '/_authenticated/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AuthenticatedCommandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab': {
      id: '/_authenticated/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/officers': {
      id: '/_authenticated/officers'
      path: '/officers'
      fullPath: '/officers'
      preLoaderRoute: typeof AuthenticatedOfficersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/register': {
      id: '/_authenticated/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticatedRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gateway-heartbeat': {
      id: '/api/public/gateway-heartbeat'
      path: '/api/public/gateway-heartbeat'
      fullPath: '/api/public/gateway-heartbeat'
      preLoaderRoute: typeof ApiPublicGatewayHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/telemetry': {
      id: '/api/stream/telemetry'
      path: '/api/stream/telemetry'
      fullPath: '/api/stream/telemetry'
      preLoaderRoute: typeof ApiStreamTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommandRoute: typeof AuthenticatedCommandRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedLabRoute: typeof AuthenticatedLabRoute
  AuthenticatedOfficersRoute: typeof AuthenticatedOfficersRoute
  AuthenticatedRegisterRoute: typeof AuthenticatedRegisterRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommandRoute: AuthenticatedCommandRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedLabRoute: AuthenticatedLabRoute,
  AuthenticatedOfficersRoute: AuthenticatedOfficersRoute,
  AuthenticatedRegisterRoute: AuthenticatedRegisterRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiPublicGatewayHeartbeatRoute: ApiPublicGatewayHeartbeatRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiStreamTelemetryRoute: ApiStreamTelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
