// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token =
      data.session?.access_token ||
      (typeof window !== 'undefined' && typeof window.localStorage?.getItem === 'function'
        ? window.localStorage.getItem('pashu_demo_token') || 'demo-token'
        : 'demo-token');
    return next({
      headers: { Authorization: `Bearer ${token}` },
    })
  },
)
